services:
  # Service 1: Đóng vai trò Server Socket
  my-java-server:
    # container cua server
    build: . #tim file Dockerfile o muc hien tai
    container_name: java-socket-server # ten cua container
    # Chạy class Server sau khi container khởi động
    command: java -cp out com.example.demo.socket.DMServerSocket #run file DMServerSocket trong project
    ports:
      #ben trai la may that, ben phai la cua container
      - "8088:8088"
    networks:
      # chi dinh server tham gia mang socket-network
      - socket-network

  # Service 2: Đóng vai trò Client Socket
  my-java-client:
    # container cua client
    build: . #tim file Dockerfile o muc hien tai
    container_name: java-socket-client # ten cua container
    # Chạy class Client. Quan trọng: Truyền biến môi trường tên server vào
    environment:
      - SERVER_HOST=my-java-server #server là container my-java-server
    # Chạy class Client
    command: java -cp out com.example.demo.socket.DMClientSocket #run file DMClientSocket trong project
    depends_on:
      #ưu tiên chạy trước
      - my-java-server # Đảm bảo server chạy trước
    networks:
      # nằm trong mang socket-network
      - socket-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  kafka:
    image: apache/kafka:latest
    container_name: demo-kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  redis:
    image: redis:latest
    container_name: demo-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

networks:
  # mang socket
  socket-network:
    # ten mang
    driver: bridge # mạng nội bộ
