spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/springboot_db
spring.datasource.username=root
spring.datasource.password=son123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# ===== AWS RDS Configuration =====
#spring.datasource.url=jdbc:mysql://demo-mysql-instance.ckvek62y8qp8.us-east-1.rds.amazonaws.com:3306/demo_db?useSSL=false
#spring.datasource.username=admin
#spring.datasource.password=Demo123#$
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===== GitHub OAuth2 Client Configuration =====
# Vui l�ng thay th? YOUR_CLIENT_ID v� YOUR_CLIENT_SECRET b?ng gi� tr? th?t t? GitHub
spring.security.oauth2.client.registration.github.client-id=Ov23li1PdCPsW6h6Wtfm
spring.security.oauth2.client.registration.github.client-secret=fe46a1f420e71714e7aed0e1e9016a5b14143ce4
spring.security.oauth2.client.registration.github.scope=read:user, user:email

# RabbitMQ configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


# --- Kafka Configuration ---
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=demo-kafka-group

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
